name: tyssue
channels:
    - conda-forge
dependencies:
    - numpy
    - scipy
    - matplotlib
    - pandas
    - pytables
    - jupyter
    - notebook
    - ipywidgets
    - pythreejs
    - ipyvolume
    - tyssue
